// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicasIgreja.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicasIgreja.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Auth.Models.CoreRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("core_roles", (string)null);
                });

            modelBuilder.Entity("Core.Auth.Models.CoreUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("core_users", (string)null);
                });

            modelBuilder.Entity("Core.Auth.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionKey")
                        .IsUnique();

                    b.ToTable("core_role_permissions", (string)null);
                });

            modelBuilder.Entity("Core.FileManagement.Models.StoredFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("FileHash");

                    b.ToTable("core_stored_files", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.AlertConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComparisonOperator")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("comparison_operator");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metric_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("ThresholdUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("threshold_unit");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_value");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("alert_configurations");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(6470),
                            Name = "Aclamação",
                            Slug = "aclamacao",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7054),
                            Name = "Adoração",
                            Slug = "adoracao",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7056),
                            Name = "Ato penitencial",
                            Slug = "ato-penitencial",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7057),
                            Name = "Comunhão",
                            Slug = "comunhao",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7058),
                            Name = "Cordeiro",
                            Slug = "cordeiro",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7060),
                            Name = "Entrada",
                            Slug = "entrada",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7061),
                            Name = "Espírito Santo",
                            Slug = "espirito-santo",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7062),
                            Name = "Final",
                            Slug = "final",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7063),
                            Name = "Glória",
                            Slug = "gloria",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7064),
                            Name = "Maria",
                            Slug = "maria",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7065),
                            Name = "Ofertório",
                            Slug = "ofertorio",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7066),
                            Name = "Pós Comunhão",
                            Slug = "pos-comunhao",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7067),
                            Name = "Salmo",
                            Slug = "salmo",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7068),
                            Name = "Santo",
                            Slug = "santo",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 175, DateTimeKind.Utc).AddTicks(7069),
                            Name = "Diversos",
                            Slug = "diversos",
                            WorkspaceId = 1
                        });
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.CustomFilterGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("ShowAsTab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_as_tab");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Slug")
                        .IsUnique();

                    b.ToTable("custom_filter_groups", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.CustomFilterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("FilterGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("filter_group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("FilterGroupId", "Slug")
                        .IsUnique();

                    b.ToTable("custom_filter_values", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.FileArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("FileId", "ArtistId")
                        .IsUnique();

                    b.ToTable("file_artists", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.FileCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FileId", "CategoryId")
                        .IsUnique();

                    b.ToTable("file_categories", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.FileCustomFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<int>("FilterValueId")
                        .HasColumnType("integer")
                        .HasColumnName("filter_value_id");

                    b.HasKey("Id");

                    b.HasIndex("FilterValueId");

                    b.HasIndex("FileId", "FilterValueId")
                        .IsUnique();

                    b.ToTable("file_custom_filters", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.MergeList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("merge_lists", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.MergeListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapoOverride")
                        .HasColumnType("integer")
                        .HasColumnName("capo_override");

                    b.Property<string>("KeyOverride")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key_override");

                    b.Property<int>("MergeListId")
                        .HasColumnType("integer")
                        .HasColumnName("merge_list_id");

                    b.Property<int>("OrderPosition")
                        .HasColumnType("integer")
                        .HasColumnName("order_position");

                    b.Property<int>("PdfFileId")
                        .HasColumnType("integer")
                        .HasColumnName("pdf_file_id");

                    b.HasKey("Id");

                    b.HasIndex("PdfFileId");

                    b.HasIndex("MergeListId", "OrderPosition");

                    b.ToTable("merge_list_items", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.PdfFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChordContent")
                        .HasColumnType("text")
                        .HasColumnName("chord_content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pdf_only")
                        .HasColumnName("content_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileHash")
                        .HasColumnType("text")
                        .HasColumnName("file_hash");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("MusicalKey")
                        .HasColumnType("text")
                        .HasColumnName("musical_key");

                    b.Property<string>("OcrError")
                        .HasColumnType("text")
                        .HasColumnName("ocr_error");

                    b.Property<DateTime?>("OcrStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocr_started_at");

                    b.Property<string>("OcrStatus")
                        .HasColumnType("text")
                        .HasColumnName("ocr_status");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_name");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("SongName")
                        .HasColumnType("text")
                        .HasColumnName("song_name");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workspace_id");

                    b.Property<string>("YoutubeLink")
                        .HasColumnType("text")
                        .HasColumnName("youtube_link");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("UploadDate")
                        .IsDescending();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("pdf_files", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.SystemEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("system_events");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.SystemMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metric_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("system_metrics");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.UserSongPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArrangementJson")
                        .HasColumnType("json")
                        .HasColumnName("arrangement_json");

                    b.Property<int>("CapoFret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("capo_fret");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PdfFileId")
                        .HasColumnType("integer")
                        .HasColumnName("pdf_file_id");

                    b.Property<int>("TransposeAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("transpose_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PdfFileId");

                    b.HasIndex("UserId", "PdfFileId")
                        .IsUnique();

                    b.ToTable("user_song_preferences", (string)null);
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("workspaces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 24, 14, 27, 49, 174, DateTimeKind.Utc).AddTicks(9752),
                            Icon = "church",
                            IsActive = true,
                            Name = "Igreja",
                            Slug = "igreja",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("Core.Auth.Models.CoreUser", b =>
                {
                    b.HasOne("Core.Auth.Models.CoreRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Auth.Models.RolePermission", b =>
                {
                    b.HasOne("Core.Auth.Models.CoreRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.AuditLog", b =>
                {
                    b.HasOne("Core.Auth.Models.CoreUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.Category", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.Workspace", "Workspace")
                        .WithMany("Categories")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.CustomFilterGroup", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.Workspace", "Workspace")
                        .WithMany("CustomFilterGroups")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.CustomFilterValue", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.CustomFilterGroup", "FilterGroup")
                        .WithMany("Values")
                        .HasForeignKey("FilterGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterGroup");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.FileArtist", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.Artist", "Artist")
                        .WithMany("FileArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicasIgreja.Api.Models.PdfFile", "PdfFile")
                        .WithMany("FileArtists")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("PdfFile");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.FileCategory", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.Category", "Category")
                        .WithMany("FileCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicasIgreja.Api.Models.PdfFile", "PdfFile")
                        .WithMany("FileCategories")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("PdfFile");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.FileCustomFilter", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.PdfFile", "PdfFile")
                        .WithMany("FileCustomFilters")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicasIgreja.Api.Models.CustomFilterValue", "FilterValue")
                        .WithMany("FileCustomFilters")
                        .HasForeignKey("FilterValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterValue");

                    b.Navigation("PdfFile");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.MergeList", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.Workspace", "Workspace")
                        .WithMany("MergeLists")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.MergeListItem", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.MergeList", "MergeList")
                        .WithMany("Items")
                        .HasForeignKey("MergeListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicasIgreja.Api.Models.PdfFile", "PdfFile")
                        .WithMany("MergeListItems")
                        .HasForeignKey("PdfFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergeList");

                    b.Navigation("PdfFile");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.PdfFile", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.Workspace", "Workspace")
                        .WithMany("PdfFiles")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.SystemEvent", b =>
                {
                    b.HasOne("Core.Auth.Models.CoreUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.UserSongPreference", b =>
                {
                    b.HasOne("MusicasIgreja.Api.Models.PdfFile", "PdfFile")
                        .WithMany()
                        .HasForeignKey("PdfFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdfFile");
                });

            modelBuilder.Entity("Core.Auth.Models.CoreRole", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.Artist", b =>
                {
                    b.Navigation("FileArtists");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.Category", b =>
                {
                    b.Navigation("FileCategories");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.CustomFilterGroup", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.CustomFilterValue", b =>
                {
                    b.Navigation("FileCustomFilters");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.MergeList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.PdfFile", b =>
                {
                    b.Navigation("FileArtists");

                    b.Navigation("FileCategories");

                    b.Navigation("FileCustomFilters");

                    b.Navigation("MergeListItems");
                });

            modelBuilder.Entity("MusicasIgreja.Api.Models.Workspace", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CustomFilterGroups");

                    b.Navigation("MergeLists");

                    b.Navigation("PdfFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
